### DISCUSSION TITLE
Is there a way to access Docker API from the SaaS Boost application?

### DISCUSSION THREAD

**Discussion by kaypee90** [awslabs/aws-saas-boost#196] [Q&A]
I want to be able to mount this volume [-v /var/run/docker.sock:/var/run/docker.sock] at the point of starting the container

**Comment by PoeppingT** [comment]
> I want to be able to mount this volume [-v /var/run/docker.sock:/var/run/docker.sock] at the point of starting the container

AWS SaaS Boost containers are hosted in ECS by default, and you can find the AWS documentation describing how you would mount specific volumes to ECS containers [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/docker-volumes.html). This is not currently available as part of tooling for AWS SaaS Boost.

That being said, [`/var/run/docker.sock`](https://stackoverflow.com/questions/35110146/can-anyone-explain-docker-sock) is the UNIX socket used by the Docker daemon to listen for [Docker API](https://docs.docker.com/engine/api/v1.41) requests, most of which are already covered by the AWS ECS API.

Can you explain a little more about what you're trying to accomplish?

**Reply by ptupitsyn** [reply]
@PoeppingT is it possible to access the Docker API and run another container from within SaaS Boost?

**Reply by PoeppingT** [reply]
As of today AWS SaaS Boost will not do this automatically for you.

The only way to access the Docker API from within a Docker image is by [running AWS ECS on EC2, rather than Fargate](https://github.com/jenkinsci/amazon-ecs-plugin/issues/137#issuecomment-658563959). If your container is Windows based, AWS SaaS Boost will automatically select EC2 as your compute platform as part of the ECS Task Definition (in [`tenant-onboarding.yaml`](https://github.com/awslabs/aws-saas-boost/blob/main/resources/tenant-onboarding.yaml#L647-L658)) otherwise, AWS SaaS Boost will automatically select Fargate. To change your SaaS Boost installation to always run on EC2, you should only need to remove the if statements linked above in `tenant-onboarding.yaml` so that the EC2 compute platform is always selected.

This isn't enough though, as you will also need to alter the ECS Task Definition in `tenant-onboarding.yaml` to have a container definition with a mount point configured as in the [ECS Cloudformation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinitions.html#cfn-ecs-taskdefinition-containerdefinition-mountpoints) to specify the `docker.sock` volume configuration. More information and details can be found in [this documentation for binding mounts on AWS ECS](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/bind-mounts.html#specify-volume-config).

**Reply by kaypee90** [reply]
@PoeppingT I updated the `tenant-onboarding.yaml` to always use EC2. Also I updated the Volume and MountPoints sections to mount docker.sock but I am getting this error `The following resource(s) failed to create: [ECSService]` trying to create a new Tenant. 
Below are my updates. Am I missing anything? 
```
ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family:
        Fn::Join: ['', ['tenant-', !Select [0, !Split ['-', !Ref TenantId]]]]
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      TaskRoleArn: !GetAtt ECSTaskRole.Arn
      RequiresCompatibilities:
          - EC2

MountPoints:
            !If
              - ProvisionEFS
              - - ContainerPath: !Ref MountPoint
                  SourceVolume: !GetAtt efs.Outputs.FileSystemId
                - ContainerPath: unix:///var/run/docker.sock 
                  SourceVolume: docker_sock
              - !If
                - ProvisionFsx
                - - ContainerPath: !Ref MountPoint
                    SourceVolume: !GetAtt fsx.Outputs.FSxFileSystemID
                - !Ref 'AWS::NoValue'
          LinuxParameters:
            Fn::If:
              - WindowsOS
              - !Ref 'AWS::NoValue'
              - InitProcessEnabled: true
          Secrets:
            Fn::If:
              - ProvisionRDS
              - - Name: DB_MASTER_USERNAME
                  ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/saas-boost/${Environment}/DB_MASTER_USERNAME
                - Name: DB_MASTER_PASSWORD
                  ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/saas-boost/${Environment}/DB_MASTER_PASSWORD
                - Name: DB_PORT
                  ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/saas-boost/${Environment}/DB_PORT
              - !Ref 'AWS::NoValue'
      Volumes:
        !If
          - ProvisionEFS
          - - Name: !GetAtt efs.Outputs.FileSystemId
              EFSVolumeConfiguration:
                FilesystemId: !GetAtt efs.Outputs.FileSystemId
            - Name: docker_sock
              Host:
                  SourcePath: unix:///var/run/docker.sock
          - !If
            - ProvisionFsx
            - - Name: !GetAtt fsx.Outputs.FSxFileSystemID
                Host:
                  SourcePath: !Sub ${FSxWindowsMountDrive}\
            - !Ref 'AWS::NoValue'
```
