### ISSUE TITLE
Tag inheritance for accurate cost analysis

### ISSUE THREAD

**Issue by muylucir** [awslabs/aws-saas-boost#210]
The tag (Tenant ID) set in ECS Task-definition is not inherited by Task.
Tags are not inherited by ECS Tasks, so ECS costs cannot be broken down accurately by tenant.

Accurate cost analysis is important in SaaS.

I modified **resources/tenant-onboarding.yaml** code and set Task to inherit the task-definition tag, and after that, ECS cost can be calculated accurately for each tenant.

```
  ECSService:
    Type: AWS::ECS::Service
    DependsOn:
      - ListenerWaitCondition
      - ClusterCapacityAssociationWaitCondition
    Properties: 
      PropagateTags: TASK_DEFINITION   #Add this line
```

<img width="1273" alt="ecs_tag" src="https://user-images.githubusercontent.com/22234099/164575956-8af86a69-c3d8-46f5-aa52-7375db15b404.png">

ECS was not included in the tenant cost before March 14, but ECS was added to the tenant cost from March 15 after changing the tag to be inherited.

Can you please add this code?

---

This is a :rocket: Feature Request
