### ISSUE TITLE
ALBRule (logical Id of CloudFormation) is failed to be created when SSL is set

### ISSUE THREAD

**Issue by rnlduaeo** [awslabs/aws-saas-boost#256]
If we set domain name and ssl cert in app config, the tenant is failed to be onboard with following error.
- ALBRule invalid request

So I ran through the code, found out that there are two identical codes in tenant-onboarding-app.yaml file. For just workaround, I removed ALBRule part and retried, and successfully onboard the tenant without issues.
```
ALBRule:
    Condition: IsPublic
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: !If [DisableAccess, fixed-response, forward]
          TargetGroupArn: !If [DisableAccess, !Ref 'AWS::NoValue', !Ref ALBTargetGroup]
          FixedResponseConfig:
            !If
              - DisableAccess
              - ContentType: text/html
                StatusCode: 200
                MessageBody: <html><body>Access to this application is disabled. Contact support if you have questions.</body></html>
              - !Ref 'AWS::NoValue'
      Conditions:
        - Field: path-pattern
          Values:
            - !Ref PublicPathRoute
      ListenerArn: !Ref ECSLoadBalancerHttpListener
      Priority: !Ref PublicPathRulePriority
  ALBSSLRule:
    Condition: IsPublicHttps
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: !If [DisableAccess, fixed-response, forward]
          TargetGroupArn: !If [DisableAccess, !Ref 'AWS::NoValue', !Ref ALBTargetGroup]
          FixedResponseConfig:
            !If
              - DisableAccess
              - ContentType: text/html
                StatusCode: 200
                MessageBody: <html><body>Access to this application is disabled. Contact support if you have questions.</body></html>
              - !Ref 'AWS::NoValue'
      Conditions:
        - Field: path-pattern
          Values:
            - !Ref PublicPathRoute
      ListenerArn: !Ref ECSLoadBalancerHttpsListener
      Priority: !Ref PublicPathRulePriority
  
```

### Reproduction Steps

just try to onboard the tenant with ssl cert, you can encounter this issue.

### Environment

  - **AWS Region  :**
  - **AWS SaaS Boost Version :**
  - **Workload OS  (Linux or Windows) :**

### Other

--- 

This is :bug: Bug Report
