### ISSUE TITLE
Cannot provison ElasticSearch nested stack 

### ISSUE THREAD

**Issue by AffiTheCreator** [awslabs/aws-saas-boost#66]
I'm trying to integrate Amazon Elasticsearch with SaaS boost, I have created a yaml file similar to the rds and efs extensions, i have also modified tenant-onboarding to fit the new extension modification. 

### Reproduction Steps

Project: https://github.com/AffiTheCreator/aws-saas-boost/tree/elasticsearch
1. Download the tenant-onboarding.yaml and tenant-onboarding-es.yaml 
2. Upload the files to the S3 bucket of saas boost
3. Provision a Tenant 

### What did you expect to happen?
A tenant to be provision with an Elasticsearch node 

### What actually happened?

The stack failed to create with status reason:

1. 
```
User: arn:aws:sts::AAAAAAAAAAA:assumed-role/sb-dev-onboarding-svc-role-eu-west-1/sb-dev-onboarding-provision is not authorized to perform: es:DescribeElasticsearchDomain on resource: arn:aws:es:eu-west-1:AAAAAAAAAAA:domain/tenant-4d1e2ae8-es-cluster (Service: AWSElasticsearch; Status Code: 403; Error Code: AccessDeniedException; Request ID: 5733a27c-dbec-4325-ba7a-7526fc374dfe; Proxy: null)
```` 
2. The following resource(s) failed to create: [ElasticsearchDomain].

### Environment

  - **AWS Region  : eu-west-1
  - **AWS SaaS Boost Version : v0
  - **Workload OS  (Linux or Windows) : Linux

### Other

This is :bug: Bug Report

**Comment by 4patelr** [comment]
The errors is happening because the execution role for the Lambda function that executes the tenant-onboarding.yaml does not have permissions for elasticsearch. Take a look at the saas-boost-svc-onboarding.yaml and the role on line 224 with:
`RoleName: !Sub sb-${Environment}-onboarding-svc-role-${AWS::Region}`.

You need to add permissions to the role for es:DescribeElasticsearchDomain and others. Take a look at https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonelasticsearchservice.html. 

Besides the onboarding-svc-role, you will need to add permissions to the onboarding-delete-tenant role in the same saas-boost-svc-onboarding.yaml allowing delete of the ES resources.

**Comment by AffiTheCreator** [comment]
@4patelr thanks for the reply :)

link (https://github.com/awslabs/aws-saas-boost/issues/66)

 So after reading the documentation I added this to the Policy that starts in line 243 ` - PolicyName: !Sub sb-${Environment}-onboarding-svc-policy-${AWS::Region}`
```  yaml
              # Elasticsearch onboarding policy
              - Effect: Allow
                Action:
                  - es:AddTags 
                  - es:CreateElasticsearchDomain  
                  - es:DescribeElasticsearchDomain
                  - es:CreateElasticsearchServiceRole
                Resource: 
                  - !Sub arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/$(Fn::GetAtt:[es.outputs.ESClusterName])/*
``` 
Also added the above to onboarding-delete-tenant role in the same way as before:
```yaml
              # Elasticsearch onboarding delete policy
              - Effect: Allow
                Action:
                  - es:DeleteElasticsearchDomain   
                  - es:DeleteElasticsearchServiceRole 
                  - es:DescribeElasticsearchDomain  
                  - es:RemoveTags 
                Resource: 
                  - !Sub arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/$(Fn::GetAtt:[es.outputs.ESClusterName])/*
```
In my tenant-onboarding-es.yaml I already defined my AccessPolicies, althought it's for dev purpose:
``` yaml
      AccessPolicies:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            AWS: '*'
          Action: "es:*"
          Resource: !Sub "arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/${ElasticsearchName}/*"
      Tags:
        - Key: Tenant
          Value: !Ref TenantId

``` 

I have also updated my repository with the new changes
